name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:  # Global environment variables
  HEADLESS: false
  HOME_PAGE_URL: "https://www.clinique.com/"
  SU_SI_PAGE_URL: "https://www.clinique.com/account/profile_preferences.tmpl"
  DASHBOARD_PAGE_URL: "https://www.clinique.com/account/index.tmpl"
  CART_PAGE_URL: "https://www.clinique.com/checkout/viewcart.tmpl"
  VALID_EMAIL: "clnqqa+1@gmail.com"
  VALID_PASSWORD: "OzzyQA123!"

jobs:

  signin-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm ci
      - run: npx playwright install
      - name: Run Login Tests
        run: npx cucumber-js --tags @signin

  cart-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm ci
      - run: npx playwright install
      - name: Run Cart Tests
        run: npx cucumber-js --tags @cart

  homepage-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm ci
      - run: npx playwright install
      - name: Run Dashboard Tests
        run: npx cucumber-js --tags @homepage
